package br.com.autotrac.testnanoclient.handlers

import br.com.autotrac.testnanoclient.consts.ApiEndpoints

object EndpointsLists {
    val parametersList = listOf(
        ApiEndpoints.GET_PARAM_IS_BAPTIZED,
        ApiEndpoints.GET_PARAM_WIFI_SSID,
        ApiEndpoints.SET_PARAM_WIFI_SSID,
        ApiEndpoints.GET_PARAM_ACCOUNT_NUMBER,
        ApiEndpoints.GET_PARAM_ALT_COMM_DEVICE_POLL_INTERVAL_S,
        ApiEndpoints.SET_PARAM_ALT_COMM_DEVICE_POLL_INTERVAL_S,
        ApiEndpoints.GET_PARAM_ALT_COMM_FIRMWARE_VERSION,
        ApiEndpoints.GET_PARAM_ALTERNATIVE_COMM_DEVICE_ADDRESS,
        ApiEndpoints.GET_PARAM_CELL_IP_ADDRESS,
        ApiEndpoints.GET_PARAM_CLIENT_LOGS_DIRECTORY,
        ApiEndpoints.GET_PARAM_COMM_UNIT_DEVICE_TYPE,
        ApiEndpoints.GET_PARAM_CURRENT_COMM_MODE,
        ApiEndpoints.GET_PARAM_EXT_DEV_COMM_TYPE,
        ApiEndpoints.SET_PARAM_EXT_DEV_COMM_TYPE,
        ApiEndpoints.GET_PARAM_FTP_LOGS_STATUS,
        ApiEndpoints.GET_PARAM_HAS_CELLULAR_SIGNAL,
        ApiEndpoints.GET_PARAM_HAS_SATELLITE_SIGNAL,
        ApiEndpoints.GET_PARAM_HAS_UPDATE_PENDING,
        ApiEndpoints.GET_PARAM_HOM_WIFI_SERIAL_DEV_FW_VERSIONLIST,
        ApiEndpoints.GET_PARAM_HW_CONTROL_DISABLE,
        ApiEndpoints.GET_PARAM_ICCID1,
        ApiEndpoints.GET_PARAM_IGNITION_STATUS,
        ApiEndpoints.GET_PARAM_IMEI1,
        ApiEndpoints.GET_PARAM_LAST_CELL_COMM_TIME,
        ApiEndpoints.GET_PARAM_LAST_CELL_CONNECTION_STATUS,
        ApiEndpoints.GET_PARAM_LAST_SAT_COMM_TIME,
        ApiEndpoints.GET_PARAM_LAST_SAT_CONNECTION_STATUS,
        ApiEndpoints.GET_PARAM_LOCAL_DISABLE_VPN_COMMUNICATION,
        ApiEndpoints.SET_PARAM_LOCAL_DISABLE_VPN_COMMUNICATION,
        ApiEndpoints.GET_PARAM_LOCAL_DISABLE_WIFI_COMMUNICATION,
        ApiEndpoints.SET_PARAM_LOCAL_DISABLE_WIFI_COMMUNICATION,
        ApiEndpoints.GET_PARAM_OUT_OF_BAND_MSG_PATH,
        ApiEndpoints.SET_PARAM_OUT_OF_BAND_MSG_PATH,
        ApiEndpoints.GET_PARAM_PHONE_PROVIDER_NAME,
        ApiEndpoints.GET_PARAM_PROXY_APPS_ON_WHITE_LIST,
        ApiEndpoints.GET_PARAM_SERVER_IP1,
        ApiEndpoints.GET_PARAM_SERVER_PORT1,
        ApiEndpoints.GET_PARAM_SERVICE_VERSION,
        ApiEndpoints.GET_PARAM_TIMEOUT_SEND_CELLULAR_MSG,
        ApiEndpoints.SET_PARAM_TIMEOUT_SEND_CELLULAR_MSG,
        ApiEndpoints.GET_PARAM_UC_ADDRESS,
        ApiEndpoints.GET_PARAM_UC_STATUS,
        ApiEndpoints.GET_PARAM_UC_SUBTYPE,
        ApiEndpoints.GET_PARAM_USER_INTERFACE_VERSION,
        ApiEndpoints.GET_PARAM_VPN_CONNECTION_STATUS,
        ApiEndpoints.GET_PARAM_WIFI_CONVERTER_SERIAL_NUMBER,
        ApiEndpoints.GET_PARAM_WIFI_IP_ADDRESS,
        ApiEndpoints.GET_PARAM_WIFI_SERIAL_DEV_FIRMWARE_VERSION
    )

    val requestsListForObservables = setOf(
        ApiEndpoints.REQ_MESSAGE_LIST,
        ApiEndpoints.REQ_MESSAGE_LIST_INBOX,
        ApiEndpoints.REQ_MESSAGE_LIST_OUTBOX,
        ApiEndpoints.REQ_MESSAGE_COUNT,
        ApiEndpoints.REQ_MESSAGE_DELETE,
        ApiEndpoints.REQ_MESSAGE_SET_AS_READ,
        ApiEndpoints.REQ_CONFIG_SERVICE_LOG,
        ApiEndpoints.REQ_FILE_OPERATION,
        ApiEndpoints.REQ_FORM_LIST,
        ApiEndpoints.REQ_GET_CHECKLIST,
        ApiEndpoints.REQ_CELL_SIGNAL,
        ApiEndpoints.REQ_WIFI_SIGNAL,
        ApiEndpoints.REQ_GET_CURRENT_DATE,
        ApiEndpoints.REQ_GET_MCT_PARAMETERS,
        ApiEndpoints.REQ_GET_POSITION_LAST,
        ApiEndpoints.REQ_POSITION_HISTORY_COUNT,
        ApiEndpoints.REQ_POSITION_HISTORY_LIST,
        ApiEndpoints.REQ_RESET_DATABASE,
    ).toList()
    val requestsList = setOf(
        ApiEndpoints.REQ_MESSAGE_LIST,
        ApiEndpoints.REQ_MESSAGE_COUNT,
        ApiEndpoints.REQ_MESSAGE_DELETE,
        ApiEndpoints.REQ_MESSAGE_SET_AS_READ,
        ApiEndpoints.REQ_CONFIG_SERVICE_LOG,
        ApiEndpoints.REQ_FILE_OPERATION,
        ApiEndpoints.REQ_FORM_LIST,
        ApiEndpoints.REQ_GET_CHECKLIST,
        ApiEndpoints.REQ_CELL_SIGNAL,
        ApiEndpoints.REQ_WIFI_SIGNAL,
        ApiEndpoints.REQ_GET_CURRENT_DATE,
        ApiEndpoints.REQ_GET_MCT_PARAMETERS,
        ApiEndpoints.REQ_GET_POSITION_LAST,
        ApiEndpoints.REQ_POSITION_HISTORY_COUNT,
        ApiEndpoints.REQ_POSITION_HISTORY_LIST,
        ApiEndpoints.REQ_RESET_DATABASE,
    ).toList()
    val listOfFilteredRequests = setOf(
        ApiEndpoints.REQ_MESSAGE_COUNT,
        ApiEndpoints.REQ_MESSAGE_LIST,
        ApiEndpoints.REQ_MESSAGE_DELETE,
        ApiEndpoints.REQ_MESSAGE_SET_AS_READ,
        ApiEndpoints.REQ_CONFIG_SERVICE_LOG,
        ApiEndpoints.REQ_FILE_OPERATION,
        ApiEndpoints.REQ_FORM_LIST,
        ApiEndpoints.REQ_GET_POSITION_LAST,
        ApiEndpoints.REQ_POSITION_HISTORY_COUNT,
        ApiEndpoints.REQ_POSITION_HISTORY_LIST,
        ApiEndpoints.SET_PARAM_EXT_DEV_COMM_TYPE,
        ApiEndpoints.SET_PARAM_ALT_COMM_DEVICE_POLL_INTERVAL_S,
        ApiEndpoints.SET_PARAM_LOCAL_DISABLE_VPN_COMMUNICATION,
        ApiEndpoints.SET_PARAM_OUT_OF_BAND_MSG_PATH,
        ApiEndpoints.SET_PARAM_WIFI_SSID,
        ApiEndpoints.SET_PARAM_LOCAL_DISABLE_WIFI_COMMUNICATION,
        ApiEndpoints.SET_PARAM_TIMEOUT_SEND_CELLULAR_MSG,
        ApiEndpoints.SEND_MESSAGE,
        ApiEndpoints.SEND_FILE_MESSAGE
    ).toList()

}